# Generated by Django 5.2.10 on 2026-01-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('CRYPTO', 'Cryptocurrency'), ('STOCK_GLOBAL', 'Global Stock'), ('STOCK_DSE', 'Dhaka Stock Exchange')], max_length=20)),
                ('api_identifier', models.CharField(blank=True, help_text='API ID for fetching data (e.g., CoinGecko ID)', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='assets.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
